# Obter a lista de usuários
GET http://localhost:3000/api/filme
Content-Type: application/json
###

# Inserir novo usuário
POST http://localhost:3000/api/filme
Content-Type: application/json

{
 "titulo": "X-men",
 "sinopse": "99999-9999",
 "dataEstreia": "2021-01-25T17:32:25.000Z"
}

###

# Alterar usuário
PUT http://localhost:3000/api/filme
Content-Type: application/json

{
 "_id": "626bdc9327d3eef0b33d9c24",
 "titulo": "X-men",
 "sinopse": "99999-9899",
 "dataEstreia": "2021-01-25T17:32:25.000Z"
}

###
# Excluir um colaborador pelo id
DELETE http://localhost:3000/filme/626bdc9327d3eef0b33d9c24
Content-Type: application/json
###

# Obter colaborador pelo id
GET http://localhost:3000/filme/626bdc9327d3eef0b33d9c24
Content-Type: application/json
###

# Obter colaborador filtrando
GET http://localhost:3000/filme/filtro/X-men
Content-Type: application/json
###
